"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { PasswordField } from "@/components/auth/password-field";
import { createClient } from "@/lib/supabase/client";

type Program={id:string;locations:{name:string;short_name:string}|null;afsc_programs:{code:string}|null};

export function SignUpForm(){
 const router=useRouter(); const [programs,setPrograms]=useState<Program[]>([]); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
 useEffect(()=>{const load=async()=>{try{const supabase=createClient(); const {data,error}=await supabase.from("location_programs").select("id, locations(name,short_name), afsc_programs(code)").eq("is_active",true); if(error)throw error; setPrograms((data??[]) as unknown as Program[])}catch{setError("Locations are temporarily unavailable. Please try again shortly.")}}; void load()},[]);
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const form=new FormData(event.currentTarget);try{const supabase=createClient();const email=String(form.get("email")||"").trim().toLowerCase();const {data,error}=await supabase.auth.signUp({email,password:String(form.get("password")),options:{emailRedirectTo:`${window.location.origin}/auth/callback`,data:{first_name:String(form.get("first_name")),last_name:String(form.get("last_name")),display_name:`${form.get("first_name")} ${form.get("last_name")}`,requested_role:String(form.get("role")),location_program_id:String(form.get("location_program_id"))}}});if(error)throw error;if(data.user?.identities?.length===0){setError("An account already exists for this email. Please sign in instead.");return}router.push(data.session?"/pending-approval?new=1":"/sign-in?registered=1")}catch(err){const message=err instanceof Error?err.message:"Unable to create account";setError(message.toLowerCase().includes("already")?"An account already exists for this email. Please sign in instead.":message)}finally{setBusy(false)}}
 return <form className="auth-form" onSubmit={submit}><div className="field-row"><label className="field"><span>First name</span><input name="first_name" autoComplete="given-name" required/></label><label className="field"><span>Last name</span><input name="last_name" autoComplete="family-name" required/></label></div><label className="field"><span>Email</span><input name="email" type="email" autoComplete="email" inputMode="email" required/></label><PasswordField autoComplete="new-password"/><label className="field"><span>Phase II location</span><select name="location_program_id" required defaultValue=""><option value="" disabled>Select your location</option>{programs.map(p=><option value={p.id} key={p.id}>{p.locations?.short_name||p.locations?.name} · {p.afsc_programs?.code}</option>)}</select></label><label className="field"><span>Requested role</span><select name="role" defaultValue="student" required><option value="student">Student</option><option value="preceptor">Preceptor</option><option value="supervisor">Supervisor</option></select></label>{error&&<div className="form-error" role="alert">{error} {error.includes("already")&&<Link href="/sign-in">Sign in</Link>}</div>}<button className="button auth-submit" disabled={busy}>{busy?"Creating account…":"Create account"}</button><p className="auth-foot">Already registered? <Link href="/sign-in">Sign in</Link></p></form>
}
