import { createServerClient } from "@supabase/ssr";
import { AuthError, AuthUnknownError } from "@supabase/supabase-js";
import { NextResponse, type NextRequest } from "next/server";

export async function proxy(request:NextRequest){let response=NextResponse.next({request});const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;if(!url||!key)return response;const supabase=createServerClient(url,key,{cookies:{getAll:()=>request.cookies.getAll(),setAll:(items)=>{items.forEach(({name,value})=>request.cookies.set(name,value));response=NextResponse.next({request});items.forEach(({name,value,options})=>response.cookies.set(name,value,options))}}});
// A stale/invalid refresh-token cookie (e.g. left over from a local database reset) makes
// getUser() throw instead of resolving to a signed-out result; treat that as signed-out.
const {data:{user}}=await supabase.auth.getUser().catch((error:unknown)=>({data:{user:null},error:error instanceof AuthError?error:new AuthUnknownError("Unable to load user",error)}));const protectedPath=request.nextUrl.pathname.startsWith("/dashboard")||request.nextUrl.pathname.startsWith("/profile");if(protectedPath&&!user){const signIn=request.nextUrl.clone();signIn.pathname="/sign-in";signIn.searchParams.set("next",request.nextUrl.pathname);return NextResponse.redirect(signIn)}if(user&&(protectedPath||request.nextUrl.pathname==="/pending-approval")){const {data:membership}=await supabase.from("memberships").select("id").eq("user_id",user.id).eq("is_active",true).limit(1);if(protectedPath&&!membership?.length){const pending=request.nextUrl.clone();pending.pathname="/pending-approval";pending.search="";return NextResponse.redirect(pending)}if(request.nextUrl.pathname==="/pending-approval"&&membership?.length){const dashboard=request.nextUrl.clone();dashboard.pathname="/dashboard";dashboard.search="";return NextResponse.redirect(dashboard)}}return response}
export const config={matcher:["/dashboard/:path*","/profile/:path*","/pending-approval","/auth/:path*"]};
